#spring:
#  application:
#    name: activity-service
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/fitness-activity
#      databases: fitness-activity
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#server:
#  port: 8082
#
#
##eureka:
##  instance:
##    preferIpAddress: true
##    ip-address: 127.0.0.1
##    instance-id: ${spring.application.name}:${server.port}
#
##  client:
##    serviceUrl:
##      defaultZone: http://localhost:8761/eureka/
#
#rabbitmq:
#  exchange:
#    name: fitness.exchange
#  queue:
#    name: activity.queue
#  routing:
#    key: activity.tracking
