#spring:
#  application:
#    name: user-services
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/fitness_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    username: root
#    password: root
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#
##  h2:
##    console:
##      enabled: true
##      path: /h2-console
#
#
#server:
#  port:
#    8081
#
#eureka:
#  instance:
#    preferIpAddress: true
#    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}:${server.port}
#
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:8761/eureka/
##      defaultZone: http://localhost:8761/eureka/